export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILURE = 'UPDATE_CATEGORY_FAILURE';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_ORDER = 'DELETE_ORDER';
export const GET_ALL_ORDER = 'GET_ALL_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SEARCH_ORDER = 'SEARCH_ORDER';
export const GET_ALL_REVIEW = 'GET_ALL_REVIEW';
export const GET_ALL_USER = 'GET_ALL_USER';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';
export const GET_HOME_DATA = 'GET_HOME_DATA';
export const GET_ALL_PRODUCT_REQUEST = 'GET_ALL_PRODUCT_REQUEST';
export const GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS';
export const GET_ALL_PRODUCT_FAILURE = 'GET_ALL_PRODUCT_FAILURE';

export const GET_INITIAL_DATA_REQUEST = 'GET_INITIAL_DATA_REQUEST ';
export const GET_INITIAL_DATA_SUCCESS = 'GET_INITIAL_DATA_SUCCESS';
export const GET_INITIAL_DATA_FAILURE = 'GET_INITIAL_DATA_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILUER = 'LOGIN_FAILUER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const GET_ALL_CATEGORY_RQ = 'GET_ALL_CATEGORY_RQ';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_FAILURE = 'GET_ALL_CATEGORY_FAILURE';

export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';

export const SET_CATEGORIES = 'SET_CATEGORIES';
