export const GET_RANDOM_PRODUCT = 'GET_RANDOM_PRODUCT';
export const PRODUCT_REVIEW = 'PRODUCT_REVIEW';
export const DELETE_PRODUCT_REVIEW = 'DELETE_PRODUCT_REVIEW';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const GET_PRODUCTS_SEARCH = 'GET_PRODUCTS_SEARCH';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FALURE = 'GET_ORDER_FALURE';
export const GET_NEW_PRODUCTS = 'GET_NEW_PRODUCTS';
export const GET_PURCHASED_PRODUCT = 'GET_PURCHASED_PRODUCT';
export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_CANCEL = 'ORDER_CANCEL';
export const GET_PRODUCT_BY_SLUG_REQUEST = 'GET_PRODUCT_BY_SLUG_REQUEST';
export const GET_PRODUCT_BY_SLUG_SUCCESS = 'GET_PRODUCT_BY_SLUG_SUCCESS';
export const GET_PRODUCT_BY_SLUG_FAILURE = 'GET_PRODUCT_BY_SLUG_FAILURE';

export const GET_ALL_CATEGORY_RQ = 'GET_ALL_CATEGORY_RQ';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_FAILURE = 'GET_ALL_CATEGORY_FAILURE';

export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILUER = 'LOGIN_FAILUER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
